apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman-01-root
  namespace: pacman-01-argocd
spec:
  project: pacman-01
  destination:
    namespace: pacman-01-argocd
    server: https://kubernetes.default.svc
  source:
    path: app-in-namespace/pacman-01/deployments
    targetRevision: main
    repoURL: https://github.com/marrober/helm-deployments.git
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
      allowEmpty: false 
    syncOptions: 
      - Validate=true 
      - CreateNamespace=true 
      - PrunePropagationPolicy=foreground 
      - PruneLast=true 
    retry:
      limit: 1 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 20s 