kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
  name: layer-1
  labels:
    app: layer-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: layer-1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: layer-1
        deployment: layer-1
    spec:
      containers:
        - name: layer-1
          image: 'image-registry.openshift-image-registry.svc:5000/prog-layers-app-01-dev-01/layers:fixed-v1'
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: THIS_LAYER_NAME
              value: layer-1
            - name: VERSION_ID
              value: v1
            - name: HEALTH_DELAY
              value: '5'
          startupProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 40
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          imagePullPolicy: Always